### ISSUE TITLE
[Widget Listview] Changing the background color of a widget will hide the divider of listview 

### ISSUE THREAD

**Issue by Vijayakumr** [commonsguy/cw-android#10]
Hi,

Currently you guys have given the widget with black color background.

If i change it to white color. i cant see the divider of a listview.

and i went to listview. there i set the divider dolor to black. for some seconds the divider is visible with black color and getting hide when opening the widget. any solutions for this?

**Comment by commonsguy** [comment]
> Currently you guys have given the widget with black color background.

This is a soon-to-be-removed issue tracker for the source code of several hundred sample projects from a book.

> any solutions for this?

If you have questions regarding Android app development, use the resources outlined at http://www.andglobe.com.
