### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by sidbindal** [commonsguy/cw-android#9]
Hi,

I am new to android and learning ti myself and probably a silly question, but while executing the code, the options menu is not visible, i mean that the icons for the menu are not visible. Though, the context menu works perfectly.

Its not entering the "onCreateOptionsMenu" (debugged).

Can you please help me out here?

**Comment by commonsguy** [comment]
This repository is for very old editions of [my book](https://commonsware.com/Android). This code is no longer maintained, as my book now uses [a different repository](http://github.com/commonsguy/cw-omnibus), as is noted in [this repository's `README`](https://github.com/commonsguy/cw-android).

I recommend that you get a newer copy of my book ([latest](https://commonsware.com/Android) or [an older free one](https://commonsware.com/Android/4-2-free)) and refer to it and the newer code samples.
